server:
  port: 8010
## INFO
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
spring:
  application:
    name: microservice-consumer-movie
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0